export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCH_POKEMON_DETAIL = "FETCH_POKEMON_DETAIL";
export const ADD_POKEMON_FAVORITE = "ADD_POKEMON_FAVORITE";
export const REMOVE_POKEMON_FAVORITE = "REMOVE_POKEMON_FAVORITE";
export const CATCH_POKEMON = "CATCH_POKEMON";
export const INSERT_POKEMON = "INSERT_POKEMON";
export const FETCH_POKEMON_FAVORITE = "FETCH_POKEMON_FAVORITE";
export const UPDATE_POKEMON = "UPDATE_POKEMON";
